version: '3.1'

services:
  web:
    container_name: deadsailornet_web
    build: .
    restart: unless-stopped
    ports:
      - 3100:2368
    volumes:
      - ./content:/var/lib/ghost/content:rw
    environment:
      url: http://localhost:3100
